register:
  rabbitmq:
    exchange: register.exchange
    queue: register.queue
    routingkey: register.routingkey
email:
  rabbitmq:
    exchange: email.exchange
    queue: email.queue
    routingkey: email.routingkey
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest