spring:
    rabbitmq:
        host: localhost
        password: guest
        port: 5672
        username: guest
    mail:
        host: smtp.gmail.com
        port: 587
        username: rrandomtestuser@gmail.com
        password: randomuser123
        properties:
            mail:
                smtp:
                    auth:
                        enable: true
                    starttls:
                        enable: true
email:
    rabbitmq:
        queue: email.queue